### ISSUE TITLE
Introduction 번역

### ISSUE THREAD

**Issue by nacyot** [dobbit/redux#1]
아직 미번역인 Introduction 파트부터 번역해보도록하겠습니다.
- [x] Ecosystem.md 
- [x] Examples.md 
- [x] Motivation.md 
- [x] PriorArt.md 
- [x] ThreePrinciples.md

혹 진행중이신 부분 있으면 알려주세요 :)

**Comment by deminoth** [comment]
바로 시작하시면 될 것 같습니다 ㅎㅎ
저는 Advanced 끝냈고 Glossary 들어가려 합니다.

**Comment by deminoth** [comment]
@nacyot 번역 진행 전에 docs의 파일을 docs_kr로 복사해서 갱신 후 번역해주세요. 업스트림에서 가져오는게 docs 뿐이라 이런 문제가 있네요...
